// Auto-generated Phase 9 suite include list
`include "test_mmu_sysmap_alignment.svh"
`include "test_mmu_sysmap_disabled.svh"
`include "test_mmu_sysmap_flag_r.svh"
`include "test_mmu_sysmap_flag_wxec.svh"
`include "test_mmu_sysmap_hit_boundary.svh"
`include "test_mmu_sysmap_hit_match.svh"
`include "test_mmu_sysmap_hit_unique.svh"
`include "test_mmu_sysmap_priority.svh"
`include "test_mmu_sysmap_priority_over_tlb.svh"
`include "test_mmu_sysmap_pte_walk_addr.svh"
`include "test_mmu_sysmap_region_config.svh"
`include "test_mmu_sysmap_region_default.svh"
`include "test_mmu_sysmap_tlb_fallback.svh"
`include "test_sysmap_hit_bypass_walk.svh"
`include "test_sysmap_multi_region_coverage.svh"
`include "test_sysmap_no_walk_required.svh"
`include "test_sysmap_vs_ptw_priority.svh"
