// Phase 13 PMP/TWU suite include list
`include "test_twu_pmp_serial.svh"
`include "test_twu_pmp_wait_stall.svh"
`include "test_ptw_pmp_before_lsu.svh"
`include "test_ptw_pmp_deny_stop.svh"
`include "test_twu_pmp_grant_onehot.svh"
`include "test_ptw_pmp_pa_1g.svh"
`include "test_ptw_pmp_pa_2m.svh"
`include "test_ptw_pmp_pa_4k.svh"
`include "test_ptw_pmp_wait_no_lsu.svh"
`include "test_ptw_pmp_pa_zero.svh"
`include "test_ptw_pmp_deny_accflt.svh"
`include "test_ptw_pmp_deny_no_refill.svh"
`include "test_ptw_pmp_mmode_l0.svh"
`include "test_twu_mask_pmp_wait_all4.svh"
`include "test_ptw_pmp_fetch_zero.svh"
`include "test_ptw_pmp_port_map_concurrent.svh"
