// =============================================================================
// mmu_dut_probes_if.sv
// Whitebox 观测：DUT 内部 net 在 tb_top 中用 assign 驱动本 interface 的 net；
// mmu_env_pkg 内 mmu_env_cg_whitebox 只持有 virtual mmu_dut_probes_if（禁止 $root）。
// =============================================================================
`ifndef MMU_DUT_PROBES_IF_SV
`define MMU_DUT_PROBES_IF_SV

interface mmu_dut_probes_if (
  input logic clk_i,
  input logic rst_ni
);
  localparam int PTW_ID_WIDTH = 7;

  // mmu_l1itlb
  wire [31:0]  l1i_entry_vld;
  wire [1:0]   l1i_ref_fsm;
  wire         l1i_credit_cnt;

  // mmu_l1dtlb
  wire [7:0]   l1d_mb_vld;       // MB_DEPTH=8
  wire [2:0]   l1d_mb_st0;       // mb_entry_state[0]
  wire [15:0]  l1d_entry_vld;
  wire [15:0][26:0] l1d_entry_vpn;
  wire [15:0][27:0] l1d_entry_ppn;
  wire [15:0][2:0]  l1d_entry_pgs;
  wire [15:0][13:0] l1d_entry_flg;
  wire [15:0]        l1d_entry_clr;
  wire [7:0][2:0]  l1d_mb_state;
  wire [7:0][26:0] l1d_mb_vpn;
  wire [7:0][27:0] l1d_mb_ppn;
  wire [7:0][2:0]  l1d_mb_pgs;
  wire [7:0][13:0] l1d_mb_flg;
  wire [7:0][6:0]  l1d_mb_iid;
  wire [7:0]   l1d_mb_issued;
  wire [7:0]   l1d_mb_ready;
  wire [7:0]   l1d_mb_wfc;
  wire [7:0]   l1d_mb_wfi;
  wire [7:0]   l1d_mb_store;
  wire [4:0]   l1d_sched_credit_cnt;
  wire         l1d_l2_credit_ret;
  wire         l1d_l2_req_vld;
  wire [26:0]  l1d_l2_req_vpn;
  wire [2:0]   l1d_l2_req_eid;
  wire         l1d_l2_req_is_load;
  wire [26:0]  l1d_p0_req_vpn;
  wire         l1d_p0_addr_hit;
  wire         l1d_p0_hit_vld;
  wire         l1d_p0_miss_vld;
  wire         l1d_p0_mb_hit;
  wire         l1d_p0_pre_sel;
  wire         l1d_p0_expt_match;
  wire [27:0]  l1d_p0_entry_pa;
  wire [27:0]  l1d_p0_off_pa;
  wire [27:0]  l1d_p0_fin_pa;
  wire [26:0]  l1d_p1_req_vpn;
  wire         l1d_p1_addr_hit;
  wire         l1d_p1_hit_vld;
  wire         l1d_p1_miss_vld;
  wire         l1d_p1_mb_hit;
  wire         l1d_p1_pre_sel;
  wire         l1d_p1_expt_match;
  wire [27:0]  l1d_p1_entry_pa;
  wire [27:0]  l1d_p1_off_pa;
  wire [27:0]  l1d_p1_fin_pa;
  wire         l1d_refill_vld;
  wire [1:0]   l1d_refill_src;
  wire [3:0]   l1d_refill_idx;
  wire [26:0]  l1d_refill_vpn;
  wire [27:0]  l1d_refill_ppn;
  wire [2:0]   l1d_refill_pgs;
  wire [13:0]  l1d_refill_flg;
  wire [15:0]  l1d_entry_upd;
  wire [7:0]   l1d_refill_gnt_bus;
  wire [6:0]   l1d_refill_iid0;
  wire [6:0]   l1d_refill_iid1;
  wire [6:0]   l1d_refill_iid_sel;
  wire [15:0]  l1d_p0_hit_vec;
  wire [3:0]   l1d_p0_hit_idx;
  wire [26:0]  l1d_p0_hit_vpn;
  wire [27:0]  l1d_p0_hit_ppn;
  wire [2:0]   l1d_p0_hit_pgs;
  wire [15:0]  l1d_p1_hit_vec;
  wire [3:0]   l1d_p1_hit_idx;
  wire [26:0]  l1d_p1_hit_vpn;
  wire [27:0]  l1d_p1_hit_ppn;
  wire [2:0]   l1d_p1_hit_pgs;
  wire         l1d_ptw_ref_mb_vld;
  wire [6:0]   l1d_ptw_ref_mb_iid;
  wire [26:0]  l1d_ptw_ref_mb_vpn;
  wire         l1d_ptw_ref_pavld;
  wire         l1d_ptw_ref_cmplt;
  wire [2:0]   l1d_ptw_ref_id;
  wire [26:0]  l1d_ptw_ref_vpn;
  wire [27:0]  l1d_ptw_ref_ppn;
  wire [13:0]  l1d_ptw_ref_flg;
  wire [2:0]   l1d_ptw_ref_pgs;
  wire         l1d_ptw_ref_pgflt;
  wire         l1d_ptw_ref_acflt;
  wire         l1d_l2_ref_pavld;
  wire         l1d_l2_ref_cmplt;
  wire [2:0]   l1d_l2_ref_eid;
  wire [26:0]  l1d_l2_ref_vpn;
  wire [27:0]  l1d_l2_ref_ppn;
  wire [13:0]  l1d_l2_ref_flg;
  wire [2:0]   l1d_l2_ref_pgs;
  wire         l1d_l2_ref_pgflt;
  wire         l1d_install_req_ptw;
  wire         l1d_install_req_l2;
  wire         l1d_install_req_wfi;
  wire         l1d_install_sel_ptw;
  wire         l1d_install_sel_l2;
  wire         l1d_install_sel_wfi;
  wire [2:0]   l1d_install_id_ptw;
  wire [2:0]   l1d_install_id_l2;
  wire [2:0]   l1d_install_id_wfi;
  wire         l1d_expt_wr0_vld;
  wire [3:0]   l1d_expt_wr0_eid;
  wire [6:0]   l1d_expt_wr0_iid;
  wire [26:0]  l1d_expt_wr0_vpn;
  wire         l1d_expt_wr0_pgflt;
  wire         l1d_expt_wr0_acflt;
  wire         l1d_expt_wr1_vld;
  wire [3:0]   l1d_expt_wr1_eid;
  wire [6:0]   l1d_expt_wr1_iid;
  wire [26:0]  l1d_expt_wr1_vpn;
  wire         l1d_expt_wr1_pgflt;
  wire         l1d_expt_wr1_acflt;
  wire         l1d_expt_pgflt0;
  wire         l1d_expt_acflt0;
  wire         l1d_expt_pgflt1;
  wire         l1d_expt_acflt1;
  wire [7:0]   l1d_expt_hit_vec;
  wire [11:0]  l1d_expt_wakeup;
  wire         l1d_expt_clear_req;
  wire         l1d_cp0_maee;
  wire [1:0]   l1d_cp0_mpp;
  wire         l1d_cp0_mprv;
  wire         l1d_cp0_mxr;
  wire         l1d_cp0_sum;
  wire [1:0]   l1d_cp0_priv_mode;
  wire [15:0]  l1d_regs_cur_asid;
  wire [27:0]  l1d_regs_satp_ppn;
  wire [3:0]   l1d_pmp_flg0;
  wire [3:0]   l1d_pmp_flg1;
  wire [4:0]   l1d_sysmap_flg0;
  wire [4:0]   l1d_sysmap_flg1;
  wire [7:0]   l1d_sysmap_hit0;
  wire [7:0]   l1d_sysmap_hit1;
  wire [27:0]  l1d_sysmap_pa0;
  wire [27:0]  l1d_sysmap_pa1;

  // mmu_l2tlb
  wire [2:0]   l2_bank0;   // way_index[0][2:0]
  wire [7:0]   l2_final_way_hit;
  wire [2:0]   l2_raw_pre_pgs0;
  wire         l2_final_vld;
  wire         l2_final_tlb_hit;
  wire         l2_miss;
  wire         l2_final_is_dtlb;
  wire [26:0]  l2_final_vpn;
  wire [27:0]  l2_final_hit_ppn;
  wire         l2_dtlb_ref_pavld;
  wire         l2_dtlb_ref_cmplt;
  wire [26:0]  l2_dtlb_ref_vpn;
  wire [27:0]  l2_dtlb_ref_ppn;

  // mmu_l2tlb — RRPV exact model observation signals
  wire         l2_arb_req;
  wire         l2_arb_write;
  wire [2:0]   l2_arb_acc_type;
  wire [7:0]   l2_arb_bank_sel;
  wire [7:0]   l2_arb_idx_w0;
  wire [7:0]   l2_arb_idx_w1;
  wire [7:0]   l2_arb_idx_w2;
  wire [7:0]   l2_arb_idx_w3;
  wire [7:0]   l2_arb_idx_w4;
  wire [7:0]   l2_arb_idx_w5;
  wire [7:0]   l2_arb_idx_w6;
  wire [7:0]   l2_arb_idx_w7;
  wire [23:0]  l2_arb_rrpv_din;
  wire [47:0]  l2_arb_tag_din;
  wire         l2_raw_vld;
  wire [7:0]   l2_raw_way_mask;
  wire [7:0]   l2_raw_way_vld;
  wire [23:0]  l2_rrpv_dout_bus;
  wire [7:0]   l2_wbuf_cam_hit;
  wire [23:0]  l2_bypassed_rrpv_rdata;
  wire         l2_final_pa_vld;
  wire [7:0]   l2_final_way_sel;
  wire [2:0]   l2_final_acc_type;
  wire [63:0]  l2_final_bank_index;
  wire [7:0]   l2_final_way_vld;
  wire [7:0]   l2_victim_way;
  wire [23:0]  l2_rrpv_updata;
  wire         l2_wbuf_push_req;
  wire         l2_wbuf_pop_grant;
  wire         l2_wbuf_empty;

  // mmu_l2tlb / x_l2tlb_reqq
  wire [8:0]   l2_reqq_vld_vec;  // TOTAL_DEPTH=9
  wire [8:0]   l2_reqq_rdy_vec;
  wire [3:0]   l2_reqq_qid;
  wire         l2_reqq_issue_valid;
  wire [2:0]   l2_reqq_issue_type;

  // mmu_l2tlb — PFU request/response pairing signals
  //   l2_pfu_req_vld: asserted when a PFU request enters the L2TLB pipeline
  //                   (final_vld && final_acc_type==3'b100)
  //   l2_pfu_req_vpn: VPN of the PFU request when l2_pfu_req_vld is high
  //   l2_pfu_rsp_vld: asserted when the PFU response is valid
  //                   (pfu_ok_st || pfu_deny_st)
  //   l2_pfu_rsp_pa:  PA result for the PFU response
  wire         l2_pfu_req_vld;
  wire [26:0]  l2_pfu_req_vpn;
  wire         l2_pfu_rsp_vld;
  wire [27:0]  l2_pfu_rsp_pa;

  // mmu_l2tlb / x_l2tlb_mb
  wire [8:0]   l2mb_vld_vec;
  wire [8:0]   l2mb_rdy_vec;
  wire         l2mb_issue_req;
  wire [PTW_ID_WIDTH-1:0]   l2mb_issue_eid;
  wire [2:0]   l2mb_issue_type;
  wire         l2mb_alloc_valid;
  wire [8:0][26:0] l2mb_entry_vpn;
  wire [8:0][2:0]  l2mb_entry_l1eid;
  wire [8:0][2:0]  l2mb_entry_type;
  wire [8:0][2:0]  l2mb_entry_queue_id;
  wire [8:0]        l2mb_entry_sent;

  // ptw
  wire [1:0]   ptw_xbar_hit_lvl;
  wire [2:0]   ptw_mbuf_twu_lvl;
  wire         ptw_fault_any;    // pgflt_vld | acc_err_vld
  wire         ptw_jtlb_ready;
  wire         ptw_twu_idle;
  wire         ptw_twu_mask;
  wire [2:0]   ptw_twu_data_ready;
  wire         ptw_mbuf_twu_have;
  wire [8:0]   ptw_mbuf_entry_vld;
  wire         ptw_twu_ref_req;
  wire         ptw_twu_pgflt_vec;
  wire         ptw_twu_acc_err_vec;
  wire         ptw_pgflt_vld;
  wire         ptw_acc_err_vld;
  wire         ptw_l2tlb_ref_pgflt;
  wire         ptw_l2tlb_ref_acc_err;
  wire         l2tlb_ptw_req;
  wire [PTW_ID_WIDTH-1:0]   l2tlb_ptw_id;
  wire [2:0]   l2tlb_ptw_type;
  wire [26:0]  l2tlb_ptw_vpn;
  wire         l1d_miss0_vld_q;
  wire         l1d_miss1_vld_q;
  wire         l1d_miss0_abort_q;
  wire         l1d_miss1_abort_q;
  wire [26:0]  l1d_miss0_vpn_q;
  wire [26:0]  l1d_miss1_vpn_q;
  wire [6:0]   l1d_miss0_iid_q;
  wire [6:0]   l1d_miss1_iid_q;
  wire         l1d_miss0_store_q;
  wire         l1d_miss1_store_q;
  wire         l1d_alloc_req0_vld;
  wire         l1d_alloc_req1_vld;
  wire         l1d_alloc_gnt0_raw;
  wire         l1d_alloc_gnt1_raw;
  wire         l1d_alloc_gnt0_safe;
  wire         l1d_alloc_gnt1_safe;
  wire [2:0]   l1d_alloc_sel0;
  wire [2:0]   l1d_alloc_sel1;
  wire [7:0]   l1d_mb_alloc_we_raw;
  wire [7:0]   l1d_mb_alloc_we_safe;
  wire [7:0]   l1d_mb_issue_sel;
  wire [7:0]   l1d_mb_issue_grant;
  wire         ptw_lsu_data_req;
  wire [39:0]  ptw_lsu_data_req_addr;
  wire         ptw_lsu_data_req_size;
  wire         ptw_lsu_data_req_raw_grant;
  wire         ptw_lsu_data_req_accept;
  wire [3:0]   ptw_lsu_data_req_id;
  wire         ptw_lsu_data_req_grant;
  wire         ptw_lsu_data_req_fire;
  wire [8:0]   ptw_lsu_data_req_grant_vec;
  wire         ptw_lsu_data_vld;
  wire         ptw_lsu_bus_error;
  wire [3:0]   ptw_lsu_data_rsp_id;
  wire [63:0]  ptw_lsu_data;
  wire         ptw_abort_drain;
  wire         ptw_mbuf_req_hold_vld;
  wire [8:0]   ptw_mbuf_req_hold_ptr;
  wire [8:0]   ptw_mbuf_req_sel_ptr;
  wire [8:0]   ptw_mbuf_req_on_ptr;
  wire [8:0]   ptw_mbuf_req_pending;
  wire [8:0]   ptw_mbuf_resp_dec;
  wire [8:0]   ptw_mbuf_data_vld_entry;
  wire [8:0]   ptw_mbuf_bus_error_entry;
  wire [8:0]   ptw_mbuf_entry_on;
  wire [8:0]   ptw_mbuf_entry_get;
  wire [8:0]   ptw_mbuf_entry_bus_err_flop;
  wire [8:0][26:0] ptw_mbuf_entry_vpn_by_id;
  wire [8:0][2:0]  ptw_mbuf_entry_type_by_id;
  wire [8:0][PTW_ID_WIDTH-1:0] ptw_mbuf_entry_source_id_by_id;
  wire         ptw_l2tlb_cmplt;
  wire         ptw_l2tlb_ref_data_vld;
  wire [PTW_ID_WIDTH-1:0]   ptw_l2tlb_id;
  wire [2:0]   ptw_l2tlb_type;
  wire [13:0]  ptw_l2tlb_flg;
  wire         ptw_l1i_ref_cmplt;
  wire         ptw_arb_req;
  wire         arb_ptw_grant;
  wire         arb_pfu_grant;
  wire         arb_l2tlb_req;
  wire [2:0]   ptw_arb_pgs;
  wire [26:0]  ptw_arb_vpn;
  wire         ptw_l1d_ref_cmplt;
  wire [2:0]   ptw_l1d_ref_id;
  wire [27:0]  ptw_l1d_ref_ppn;
  wire [47:0]  ptw_arb_ref_tag_din;
  wire [41:0]  ptw_arb_ref_data_din;
  wire [15:0]  regs_ptw_cur_asid;
  wire [27:0]  regs_ptw_satp_ppn;
  wire         ptw_cp0_maee;
  wire [1:0]   ptw_cp0_mpp;
  wire         ptw_cp0_mprv;
  wire         ptw_cp0_mxr;
  wire         ptw_cp0_sum;
  wire [1:0]   ptw_cp0_priv_mode;
  wire         tlboper_ptw_abort;
  wire         ptw_abort_flop;
  wire [26:0]  ptw_mbuf_twu_vpn;
  wire [2:0]   ptw_mbuf_twu_type;
  wire [PTW_ID_WIDTH-1:0]   ptw_mbuf_twu_id;
  wire [2:0]   ptw_mbuf_twu_lvl_vec;
  wire [63:0]  ptw_mbuf_twu_data;
  wire         ptw_mbuf_twu_data_vld;
  wire         ptw_twu_mbuf_req;
  wire [39:0] ptw_twu_mbuf_paddr;
  wire [26:0] ptw_twu_mbuf_vpn;
  wire [2:0]  ptw_twu_mbuf_type;
  wire [PTW_ID_WIDTH-1:0]  ptw_twu_mbuf_id;
  wire [2:0]  ptw_twu_mbuf_lvl;
  wire         pde_cache_req;
  wire         pde_cache_ready;
  wire         pde_cache_clear;
  wire         pde_l1_hit_vld;
  wire         pde_l2_hit_vld;
  wire [27:0]  pde_xbar_ppn;
  wire [26:0]  pde_xbar_vpn;
  wire [2:0]   pde_xbar_type;
  wire [PTW_ID_WIDTH-1:0]   pde_xbar_id;
  wire         pde_cache_update;
  wire [1:0]   pde_cache_update_level;
  wire [27:0]  pde_cache_update_ppn;
  wire [26:0]  pde_cache_update_vpn;
  wire [3:0]   pde_cache_update_l1pmpflg;
  wire [3:0]   pde_cache_update_l2pmpflg;
  wire [15:0]  pde_l1_update_vec;
  wire [15:0]  pde_l2_update_vec;
  wire [15:0]  pde_l1_valid_vec;
  wire [15:0]  pde_l2_valid_vec;
  wire [15:0]  pde_l1_plru_ref_num;
  wire [15:0]  pde_l2_plru_ref_num;
  wire         pde_l1_refill_vld;
  wire         pde_l2_refill_vld;
  wire [15:0]  pde_l1_tag_hit_vec;
  wire [15:0]  pde_l2_tag_hit_vec;
  wire [15:0][3:0] pde_l1_cached_l1pmpflg_vec;
  wire [15:0][3:0] pde_l2_cached_l1pmpflg_vec;
  wire [15:0][3:0] pde_l2_cached_l2pmpflg_vec;
  wire [7:0]   ptw_twu_mbuf_pmpflg;
  wire [7:0]   ptw_mbuf_twu_pmpflg;
  wire [8:0][7:0] ptw_mbuf_entry_pmpflg;
  wire         pde_cache_acc_err_vld;
  wire [2:0]   pde_cache_acc_err_type;
  wire [PTW_ID_WIDTH-1:0]   pde_cache_acc_err_id;
  wire         pde_cache_acc_err_grant;
  wire [15:0]  pde_l2_entry_acc_err_vec;
  wire [2:0]   ptw_acc_err_grant_vec;
  wire         pmp_regs_update_probe;
  wire         maee_leaf_lvl1_hit;
  wire         maee_leaf_lvl2_hit;
  wire         maee_leaf_lvl3_hit;
  wire         maee_csr_path_hit;
  wire         maee_refill_path_hit;

  // Phase 13 PMP/TWU and SysMap/TWU probes.
  wire [2:0] p13_pmp_vld_vec;
  wire [2:0] p13_pmp_grant_vec;
  wire [2:0] p13_pmp_deny_vec;
  wire [2:0] p13_pmp_wait_vec;
  wire [2:0] p13_pmp_mbuf_req_vec;
  wire [2:0][2:0] p13_pmp_type_vec;
  wire [3:0] p13_pmp_flg_vec;
  wire [27:0] p13_pmp_pa_vec;
  wire       p13_pmp_fetch_vec;
  wire [3:0] pfu_pmp_flg4;
  wire [4:0] pfu_sysmap_flg4;
  wire       pfu_l2tlb_deny;
  wire       pfu_l2tlb_acc_fault;
  wire       pfu_l2tlb_flag_fault;
  wire [4:0] p13_sysmap_flg_vec;
  wire [7:0] p13_sysmap_hit_vec;
  wire [27:0] p13_sysmap_pa_vec;
  wire [39:0] p13_twu_sysmap_adder_vec;
  wire       p13_twu_csr_cross_vec;
  wire       p13_twu_crs2_1g_vec;
  wire       p13_twu_crs2_2m_vec;
  wire       p13_twu_crs2_chk_vec;
  wire       p13_csr_refill_req_vec;
  wire [2:0] p13_csr_refill_pgs_vec;
  wire [41:0] p13_csr_refill_data_vec;

  // ct_mmu_tlboper
  wire [3:0]   tlbiva_cur_st;
  wire         rtu_yy_xx_flush;
  wire         tlboper_utlb_clr;
  wire         tlboper_utlb_inv_va_req;
  wire [26:0]  tlboper_utlb_inv_va;
  wire         biu_mmu_smp_disable;

  // ct_mmu_tlboper — TLBOP exact transaction decode signals
  wire [1:0]   tlbop_tlbp_fsm;
  wire [1:0]   tlbop_tlbr_fsm;
  wire [1:0]   tlbop_tlbwi_fsm;
  wire [1:0]   tlbop_tlbwr_fsm;
  wire [2:0]   tlbop_tlbiasid_fsm;
  wire         tlbop_tlbiall_fsm;
  wire         tlbop_arb_req;
  wire         tlbop_arb_write;
  wire         tlbop_arb_grant;
  wire         tlbop_regs_cmplt;
  wire         tlbop_regs_tlbp_cmplt;
  wire         tlbop_regs_tlbr_cmplt;
  // Register request triggers
  wire         tlbop_regs_req_tlbp;
  wire         tlbop_regs_req_tlbr;
  wire         tlbop_regs_req_tlbwi;
  wire         tlbop_regs_req_tlbwr;
  wire [26:0]  tlbop_regs_cur_vpn;
  wire [15:0]  tlbop_regs_cur_asid;
  wire [2:0]   tlbop_regs_cur_pgs;
  wire [11:0]  tlbop_regs_mir;
  wire [27:0]  tlbop_regs_cur_ppn;
  wire [13:0]  tlbop_regs_cur_flg;
  wire         tlbop_regs_cur_g;
  // L2TLB TLBOP response
  wire         tlbop_l2_hit;
  wire         tlbop_l2_hit_mult;
  wire [10:0]  tlbop_l2_tlbp_hit_idx;
  wire [26:0]  tlbop_l2_tlbr_vpn;
  wire [2:0]   tlbop_l2_tlbr_pgs;
  wire [15:0]  tlbop_l2_tlbr_asid;
  wire [27:0]  tlbop_l2_tlbr_ppn;
  wire [13:0]  tlbop_l2_tlbr_flg;
  wire         tlbop_l2_tlbr_g;
  wire         tlbop_l2_tlboper_cmplt;
  wire [7:0]   tlbop_l2_tlboper_sel;
  wire         tlbop_l2_va_hit;
  wire         tlbop_l2_asid_hit;
  logic        tlbop_reset_inject_active;
  logic        tlbop_reset_inject_hit;
  logic        tlbop_reset_inject_done;

  // Monitor clocking
  clocking mon_cb @(posedge clk_i);
    default input #1step;
    input l1i_entry_vld, l1i_ref_fsm, l1i_credit_cnt;
    input l1d_mb_vld, l1d_mb_st0;
    input l1d_entry_vld, l1d_entry_vpn, l1d_entry_ppn, l1d_entry_pgs, l1d_entry_flg;
    input l1d_entry_clr, l1d_mb_state, l1d_mb_vpn, l1d_mb_ppn, l1d_mb_pgs, l1d_mb_flg, l1d_mb_iid;
    input l1d_mb_issued;
    input l1d_mb_ready, l1d_mb_wfc, l1d_mb_wfi, l1d_mb_store;
    input l1d_sched_credit_cnt, l1d_l2_credit_ret, l1d_l2_req_vld, l1d_l2_req_vpn;
    input l1d_l2_req_eid, l1d_l2_req_is_load;
    input l1d_p0_req_vpn, l1d_p0_addr_hit, l1d_p0_hit_vld, l1d_p0_miss_vld, l1d_p0_mb_hit;
    input l1d_p0_pre_sel, l1d_p0_expt_match, l1d_p0_entry_pa, l1d_p0_off_pa, l1d_p0_fin_pa;
    input l1d_p1_req_vpn, l1d_p1_addr_hit, l1d_p1_hit_vld, l1d_p1_miss_vld, l1d_p1_mb_hit;
    input l1d_p1_pre_sel, l1d_p1_expt_match, l1d_p1_entry_pa, l1d_p1_off_pa, l1d_p1_fin_pa;
    input l1d_refill_vld, l1d_refill_src, l1d_refill_idx, l1d_refill_vpn, l1d_refill_ppn;
    input l1d_refill_pgs, l1d_refill_flg, l1d_entry_upd, l1d_refill_gnt_bus;
    input l1d_refill_iid0, l1d_refill_iid1, l1d_refill_iid_sel;
    input l1d_p0_hit_vec, l1d_p0_hit_idx, l1d_p0_hit_vpn, l1d_p0_hit_ppn, l1d_p0_hit_pgs;
    input l1d_p1_hit_vec, l1d_p1_hit_idx, l1d_p1_hit_vpn, l1d_p1_hit_ppn, l1d_p1_hit_pgs;
    input l1d_ptw_ref_mb_vld, l1d_ptw_ref_mb_iid, l1d_ptw_ref_mb_vpn;
    input l1d_ptw_ref_pavld, l1d_ptw_ref_cmplt, l1d_ptw_ref_id, l1d_ptw_ref_vpn;
    input l1d_ptw_ref_ppn, l1d_ptw_ref_flg, l1d_ptw_ref_pgs, l1d_ptw_ref_pgflt, l1d_ptw_ref_acflt;
    input l1d_l2_ref_pavld, l1d_l2_ref_cmplt, l1d_l2_ref_eid, l1d_l2_ref_vpn;
    input l1d_l2_ref_ppn, l1d_l2_ref_flg, l1d_l2_ref_pgs, l1d_l2_ref_pgflt;
    input l1d_miss0_vld_q, l1d_miss1_vld_q, l1d_miss0_abort_q, l1d_miss1_abort_q;
    input l1d_miss0_vpn_q, l1d_miss1_vpn_q, l1d_miss0_iid_q, l1d_miss1_iid_q;
    input l1d_miss0_store_q, l1d_miss1_store_q;
    input l1d_alloc_req0_vld, l1d_alloc_req1_vld;
    input l1d_alloc_gnt0_raw, l1d_alloc_gnt1_raw, l1d_alloc_gnt0_safe, l1d_alloc_gnt1_safe;
    input l1d_alloc_sel0, l1d_alloc_sel1, l1d_mb_alloc_we_raw, l1d_mb_alloc_we_safe;
    input l1d_mb_issue_sel, l1d_mb_issue_grant;
    input l1d_install_req_ptw, l1d_install_req_l2, l1d_install_req_wfi;
    input l1d_install_sel_ptw, l1d_install_sel_l2, l1d_install_sel_wfi;
    input l1d_install_id_ptw, l1d_install_id_l2, l1d_install_id_wfi;
    input l1d_expt_wr0_vld, l1d_expt_wr0_eid, l1d_expt_wr0_iid, l1d_expt_wr0_vpn;
    input l1d_expt_wr0_pgflt, l1d_expt_wr0_acflt;
    input l1d_expt_wr1_vld, l1d_expt_wr1_eid, l1d_expt_wr1_iid, l1d_expt_wr1_vpn;
    input l1d_expt_wr1_pgflt, l1d_expt_wr1_acflt;
    input l1d_expt_pgflt0, l1d_expt_acflt0, l1d_expt_pgflt1, l1d_expt_acflt1;
    input l1d_expt_hit_vec, l1d_expt_wakeup, l1d_expt_clear_req;
    input l1d_cp0_maee, l1d_cp0_mpp, l1d_cp0_mprv, l1d_cp0_mxr, l1d_cp0_sum, l1d_cp0_priv_mode;
    input l1d_regs_cur_asid, l1d_regs_satp_ppn;
    input l1d_pmp_flg0, l1d_pmp_flg1;
    input l1d_sysmap_flg0, l1d_sysmap_flg1, l1d_sysmap_hit0, l1d_sysmap_hit1;
    input l1d_sysmap_pa0, l1d_sysmap_pa1;
    input l2_bank0, l2_final_way_hit, l2_raw_pre_pgs0, l2_final_vld, l2_final_tlb_hit;
    input l2_miss, l2_final_is_dtlb, l2_final_vpn, l2_final_hit_ppn;
    input l2_dtlb_ref_pavld, l2_dtlb_ref_cmplt, l2_dtlb_ref_vpn, l2_dtlb_ref_ppn;
    input l2_arb_req, l2_arb_write, l2_arb_acc_type, l2_arb_bank_sel;
    input l2_arb_idx_w0, l2_arb_idx_w1, l2_arb_idx_w2, l2_arb_idx_w3;
    input l2_arb_idx_w4, l2_arb_idx_w5, l2_arb_idx_w6, l2_arb_idx_w7;
    input l2_arb_rrpv_din, l2_arb_tag_din;
    input l2_raw_vld, l2_raw_way_mask, l2_raw_way_vld;
    input l2_rrpv_dout_bus, l2_wbuf_cam_hit, l2_bypassed_rrpv_rdata;
    input l2_final_pa_vld, l2_final_way_sel, l2_final_acc_type;
    input l2_final_bank_index, l2_final_way_vld;
    input l2_victim_way, l2_rrpv_updata;
    input l2_wbuf_push_req, l2_wbuf_pop_grant, l2_wbuf_empty;
    input l2_reqq_vld_vec, l2_reqq_rdy_vec, l2_reqq_qid, l2_reqq_issue_valid, l2_reqq_issue_type;
    input l2_pfu_req_vld, l2_pfu_req_vpn, l2_pfu_rsp_vld, l2_pfu_rsp_pa;
    input l2mb_vld_vec, l2mb_rdy_vec, l2mb_issue_req, l2mb_issue_eid, l2mb_issue_type, l2mb_alloc_valid;
    input l2mb_entry_vpn, l2mb_entry_l1eid, l2mb_entry_type, l2mb_entry_queue_id, l2mb_entry_sent;
    input ptw_xbar_hit_lvl, ptw_mbuf_twu_lvl, ptw_fault_any;
    input ptw_jtlb_ready, ptw_twu_idle, ptw_twu_mask, ptw_twu_data_ready;
    input ptw_mbuf_twu_have, ptw_mbuf_entry_vld;
    input ptw_twu_ref_req, ptw_twu_pgflt_vec, ptw_twu_acc_err_vec;
    input ptw_pgflt_vld, ptw_acc_err_vld, ptw_l2tlb_ref_pgflt, ptw_l2tlb_ref_acc_err;
    input l2tlb_ptw_req, l2tlb_ptw_id, l2tlb_ptw_type, l2tlb_ptw_vpn;
    input ptw_lsu_data_req, ptw_lsu_data_req_addr, ptw_lsu_data_req_size;
    input ptw_lsu_data_req_raw_grant, ptw_lsu_data_req_accept;
    input ptw_lsu_data_req_id, ptw_lsu_data_req_grant, ptw_lsu_data_req_fire;
    input ptw_lsu_data_req_grant_vec, ptw_lsu_data_vld, ptw_lsu_bus_error, ptw_lsu_data;
    input ptw_lsu_data_rsp_id;
    input ptw_abort_drain, ptw_mbuf_req_hold_vld, ptw_mbuf_req_hold_ptr;
    input ptw_mbuf_req_sel_ptr, ptw_mbuf_req_on_ptr, ptw_mbuf_req_pending;
    input ptw_mbuf_resp_dec, ptw_mbuf_data_vld_entry, ptw_mbuf_bus_error_entry;
    input ptw_mbuf_entry_on, ptw_mbuf_entry_get, ptw_mbuf_entry_bus_err_flop;
    input ptw_mbuf_entry_vpn_by_id, ptw_mbuf_entry_type_by_id;
    input ptw_mbuf_entry_source_id_by_id;
    input ptw_l2tlb_cmplt, ptw_l2tlb_ref_data_vld, ptw_l2tlb_id, ptw_l2tlb_type;
    input ptw_l2tlb_flg, ptw_l1i_ref_cmplt;
    input ptw_arb_req, arb_ptw_grant, arb_pfu_grant, arb_l2tlb_req;
    input ptw_arb_pgs, ptw_arb_vpn, ptw_l1d_ref_cmplt, ptw_l1d_ref_id, ptw_l1d_ref_ppn;
    input ptw_arb_ref_tag_din, ptw_arb_ref_data_din;
    input regs_ptw_cur_asid, regs_ptw_satp_ppn;
    input ptw_cp0_maee, ptw_cp0_mpp, ptw_cp0_mprv, ptw_cp0_mxr, ptw_cp0_sum, ptw_cp0_priv_mode;
    input tlboper_ptw_abort, ptw_abort_flop;
    input ptw_mbuf_twu_vpn, ptw_mbuf_twu_type, ptw_mbuf_twu_id, ptw_mbuf_twu_lvl_vec;
    input ptw_mbuf_twu_data, ptw_mbuf_twu_data_vld;
    input ptw_twu_mbuf_req, ptw_twu_mbuf_paddr, ptw_twu_mbuf_vpn;
    input ptw_twu_mbuf_type, ptw_twu_mbuf_id, ptw_twu_mbuf_lvl;
    input pde_cache_req, pde_cache_ready, pde_cache_clear, pde_l1_hit_vld, pde_l2_hit_vld;
    input pde_xbar_ppn, pde_xbar_vpn, pde_xbar_type, pde_xbar_id;
    input pde_cache_update, pde_cache_update_level, pde_cache_update_ppn, pde_cache_update_vpn;
    input pde_cache_update_l1pmpflg, pde_cache_update_l2pmpflg;
    input pde_l1_update_vec, pde_l2_update_vec, pde_l1_valid_vec, pde_l2_valid_vec;
    input pde_l1_plru_ref_num, pde_l2_plru_ref_num, pde_l1_refill_vld, pde_l2_refill_vld;
    input pde_l1_tag_hit_vec, pde_l2_tag_hit_vec;
    input pde_l1_cached_l1pmpflg_vec, pde_l2_cached_l1pmpflg_vec, pde_l2_cached_l2pmpflg_vec;
    input ptw_twu_mbuf_pmpflg, ptw_mbuf_twu_pmpflg, ptw_mbuf_entry_pmpflg;
    input pde_cache_acc_err_vld, pde_cache_acc_err_type, pde_cache_acc_err_id;
    input pde_cache_acc_err_grant, pde_l2_entry_acc_err_vec, ptw_acc_err_grant_vec;
    input pmp_regs_update_probe;
    input maee_leaf_lvl1_hit, maee_leaf_lvl2_hit, maee_leaf_lvl3_hit;
    input maee_csr_path_hit, maee_refill_path_hit;
    input p13_pmp_vld_vec, p13_pmp_grant_vec, p13_pmp_deny_vec;
    input p13_pmp_wait_vec, p13_pmp_mbuf_req_vec, p13_pmp_type_vec;
    input p13_pmp_flg_vec, p13_pmp_pa_vec, p13_pmp_fetch_vec;
    input pfu_pmp_flg4, pfu_sysmap_flg4, pfu_l2tlb_deny;
    input pfu_l2tlb_acc_fault, pfu_l2tlb_flag_fault;
    input p13_sysmap_flg_vec, p13_sysmap_hit_vec, p13_sysmap_pa_vec;
    input p13_twu_sysmap_adder_vec, p13_twu_csr_cross_vec;
    input p13_twu_crs2_1g_vec, p13_twu_crs2_2m_vec, p13_twu_crs2_chk_vec;
    input p13_csr_refill_req_vec, p13_csr_refill_pgs_vec, p13_csr_refill_data_vec;
    input tlbiva_cur_st, rtu_yy_xx_flush, tlboper_utlb_clr, tlboper_utlb_inv_va_req;
    input tlboper_utlb_inv_va;
    input biu_mmu_smp_disable;
    input tlbop_tlbp_fsm, tlbop_tlbr_fsm, tlbop_tlbwi_fsm, tlbop_tlbwr_fsm;
    input tlbop_tlbiasid_fsm, tlbop_tlbiall_fsm;
    input tlbop_arb_req, tlbop_arb_write, tlbop_arb_grant;
    input tlbop_regs_cmplt, tlbop_regs_tlbp_cmplt, tlbop_regs_tlbr_cmplt;
    input tlbop_regs_req_tlbp, tlbop_regs_req_tlbr, tlbop_regs_req_tlbwi, tlbop_regs_req_tlbwr;
    input tlbop_regs_cur_vpn, tlbop_regs_cur_asid, tlbop_regs_cur_pgs, tlbop_regs_mir;
    input tlbop_regs_cur_ppn, tlbop_regs_cur_flg, tlbop_regs_cur_g;
    input tlbop_l2_hit, tlbop_l2_hit_mult, tlbop_l2_tlbp_hit_idx;
    input tlbop_l2_tlbr_vpn, tlbop_l2_tlbr_pgs, tlbop_l2_tlbr_asid;
    input tlbop_l2_tlbr_ppn, tlbop_l2_tlbr_flg, tlbop_l2_tlbr_g;
    input tlbop_l2_tlboper_cmplt, tlbop_l2_tlboper_sel;
    input tlbop_l2_va_hit, tlbop_l2_asid_hit;
    input tlbop_reset_inject_active, tlbop_reset_inject_hit, tlbop_reset_inject_done;
  endclocking

endinterface : mmu_dut_probes_if

`endif // MMU_DUT_PROBES_IF_SV
