// Auto-generated Phase 9 suite include list
`include "test_mmu_csr_complete_signal.svh"
`include "test_mmu_csr_cskyee.svh"
`include "test_mmu_csr_dual_satp_sel.svh"
`include "test_mmu_csr_icg_disable.svh"
`include "test_mmu_csr_icg_enable.svh"
`include "test_mmu_csr_maee.svh"
`include "test_mmu_csr_mode_disable.svh"
`include "test_mmu_csr_mode_sv39.svh"
`include "test_mmu_csr_no_op.svh"
`include "test_mmu_csr_ptw_disable.svh"
`include "test_mmu_csr_satp_fields.svh"
`include "test_mmu_csr_satp_read.svh"
`include "test_mmu_csr_satp_read_both.svh"
`include "test_mmu_csr_satp_switch.svh"
`include "test_mmu_csr_satp_write.svh"
`include "test_mmu_csr_satp_write_tlb_inval.svh"
