// Auto-generated Phase 9 suite include list
`include "test_mmu_pmp_8port_concurrent.svh"
`include "test_mmu_pmp_cross_port_deny.svh"
`include "test_mmu_pmp_deny_access_fault.svh"
`include "test_mmu_pmp_deny_fetch_fault.svh"
`include "test_mmu_pmp_fetch_selective.svh"
`include "test_mmu_pmp_flg_combinations.svh"
`include "test_mmu_pmp_flg_encode.svh"
`include "test_mmu_pmp_pa_alignment.svh"
`include "test_mmu_pmp_pa_correctness.svh"
`include "test_mmu_pmp_pa_pipeline.svh"
`include "test_mmu_pmp_pde_cache_flow.svh"
`include "test_mmu_pmp_port_config_independence.svh"
`include "test_mmu_pmp_port_independence.svh"
`include "test_mmu_pmp_port_saturation.svh"
`include "test_mmu_pmp_cfg_coverage_sweep.svh"
`include "test_pmp_deny_walk_abort.svh"
